// const url='http://127.0.0.1:5000/'
const url='https://freddyabad.pythonanywhere.com/'
export const API_URL_REGISTRO = url+'register';
export const API_URL_LOGIN = url+'login';
export const API_URL_BUSCAR_AMENAZA = url+'gsb/buscar_amenazas';
export const API_URL_GSB_LISTAR_NAVEGACION = url+'gsb/listas_navegacion';
export const API_URL_VT_CONSULTAR_ARCHIVOS_IP = url+'virus_total/consultar_archivo_ips';
export const API_URL_VT_CONSULTAR_IP = url+'virus_total/consultar_ip';
export const API_URL_IPINFO = url+'ipinfo/verificar_ip';
export const API_URL_GETUSERS = url+'get_users';
